import type { Metadata } from "next";
import { Nunito, Lexend_Deca } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/lib/providers/theme-provider";

const nunito = Nunito({
	variable: "--font-nunito",
	subsets: ["latin"],
});

const lexendDeca = Lexend_Deca({
	variable: "--font-lexend-deca",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link rel="icon" href="/favicon.svg" type="image/svg+xml"></link>
			</head>
			<body className={`${nunito.variable} ${lexendDeca.variable} antialiased`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<div className="max-w-5xl mx-auto">
						<Navbar />
						{children}
					</div>
				</ThemeProvider>
			</body>
		</html>
	);
}
